config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'patients/graph', to: 'patients#graph'
  resources :patients
  get 'static_pages/landing_page'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#landing_page"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    if user.receptionist?
      can [:read, :create, :update, :destroy], Patient
    elsif user.doctor?
      can [:read, :graph], Patient
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def doctor?
    self.role == 'doctor'? true : false
  end

  def receptionist?
    self.role == 'receptionist'? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  def graph

  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :age, :gender)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/_alert.html.erb
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">DocPortal</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if user_signed_in?  %>
            <a class="nav-link active" aria-current="page" href="/patients">Patients</a>
          <% end %>
        </li>
        <li class="nav-item">
          <% if user_signed_in? && current_user.doctor?%>
            <a class="nav-link active" aria-current="page" href="/patients/graph">Patients Graph</a>
          <% end %>
        </li>
        
        
      </ul>
      
      <span class="nav-login">
        <% if user_signed_in? %>
          <%= current_user.email %> | 
          <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path %> 
        <% end %>
      </span>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'application', "data-turbo-track": "reload" %>
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_importmap_tags %>
  <title>DocPortal</title>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <% if notice %>
      <%= render 'layouts/notice' %>
    <% elsif alert %>
      <%= render 'layouts/alert' %>
    <% end %>
    <br>
    <div class="container">
      <%= yield %>
    </div> 
  </div>
</body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p>
    <strong>Name:</strong>
    <%= patient.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= patient.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= patient.gender %>
  </p>

</div>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient %> |
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/graph.html.erb
<%= line_chart Patient.group_by_day(:created_at).count %>

app/views/patients/index.html.erb
<h1>Patients</h1>

<div id="patients">
  <% @patients.each do |patient| %>
    <%= render patient %>
    <p>
      <%= link_to "Show this patient", patient %>
    </p>
  <% end %>
</div>

<%= link_to "New patient", new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<%= render @patient %>

<div>
  <%= link_to "Edit this patient", edit_patient_path(@patient) %> |
  <%= link_to "Back to patients", patients_path %>

  <%= button_to "Destroy this patient", @patient, method: :delete %>
</div>

app/views/static_pages/landing_page.html.erb
<% if user_signed_in? %> 
	<%= link_to 'Go to Patients', patients_path %> | 
	<% if current_user.doctor? %>
  		<%= link_to 'View the Patient Graph', "/patients/graph"%>
  	<% end %>
<% else %>
	<p> Please Sign in to Get Access to the App </p>
<% end %>